#!/bin/bash

SYMBOLSFILE="$PWD/symbols"
SHOULD_COPY=false

if [ -f "$HOME/.unipickerrc" ]; then
    source "$HOME/.unipickerrc"
fi

if [ "$UNIPICKER_SELECT_COMMAND" != "" ]; then
    SELECT_COMMAND="$UNIPICKER_SELECT_COMMAND"
elif [ "$SELECT_COMMAND" = "" ]; then
    SELECT_COMMAND="fzf"
fi

if [ "$UNIPICKER_COPY_COMMAND" != "" ]; then
    COPY_COMMAND="$UNIPICKER_COPY_COMMAND"
elif [ "$COPY_COMMAND" = "" ];then 
    # TODO Darwin / macOS command
    COPY_COMMAND="xclip -selection clipboard"
fi

usage () {
  echo "Select unicode character by description"
  echo ""
  echo "Usage: unipicker [--copy] [--list]"
  echo ""
  echo "Options:"
  echo "    --copy   Copy to clipboard"
  echo "    --list   Only list the symbols, do not select or copy"
  echo ""
  echo "Variables:"
  echo ""
  echo "  UNIPICKER_SELECT_COMMAND Command to use for selecting (= '$SELECT_COMMAND')"
  echo "  UNIPICKER_COPY_COMMAND   Command to use for copying (= '$COPY_COMMAND')"
}

while [ -n "$1" ];do
    case "$1" in
        --copy) SHOULD_COPY=true ;;
        --list) cat "$SYMBOLSFILE"; exit ;;
        -h|--help) usage; exit ;;
    esac
    shift
done

letter=$(cat "$SYMBOLSFILE" | eval $SELECT_COMMAND | sed -r 's/(.)(.*)/\1/g')

if [ $? -eq 0 ]; then
    echo "$letter"
    if [ "$SHOULD_COPY" = true ];then
        echo -n "$letter" | $COPY_COMMAND
    fi
fi
